import React, {useState} from 'react';
import {
  View,
  Text,
  Image,
  TouchableOpacity,
  Modal,
  Button,
  StyleSheet,
  Linking,
} from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';
import color from '../../../theme/color';
import {CustomStatusbar, Header} from '../../../components/componentsIndex';

const EstablishmentList = () => {
  const [modalVisible, setModalVisible] = useState(false);
  const [deleteModalVisible, setDeleteModalVisible] = useState(false);

  const establishment = {
    id: 1,
    user: 'Apna care',
    email: 'Company@gmail.com',
    generatedBy: 'White Technology',
    banner: 'https://res.cloudinary.com/dk/image/upload/v1689845782/sample.jpg',
    googleReviewUrl: 'https://maps.google.com/?cid=123456789',
    date: '2025-05-12T07:25:28.000Z',
  };

  const handleDelete = () => {
    setDeleteModalVisible(false);
    console.log('Deleted establishment:', establishment.id);
  };

  return (
    <View style={styles.container}>
      <CustomStatusbar
        backgroundColor={color.secondaryBG}
        barStyle="dark-content"
      />
      <Header
        lable="Establishment List"
        showBackIcon
        containerStyle={styles.headerStyle}
      />
      <View style={styles.card}>
        <Image source={{uri: establishment.banner}} style={styles.banner} />
        <View style={styles.infoSection}>
          <Text style={styles.title}>{establishment.user}</Text>
          <Text style={styles.generatedBy}>{establishment.generatedBy}</Text>
          <Text style={styles.emaiStyle}>{establishment.email}</Text>
          <View style={styles.actionButtons}>
            <TouchableOpacity
              onPress={() => setModalVisible(true)}
              style={styles.iconButton}>
              <Icon name="eye-outline" size={24} color="#007BFF" />
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setDeleteModalVisible(true)}
              style={styles.iconButton}>
              <Icon name="trash-outline" size={24} color="red" />
            </TouchableOpacity>
          </View>
        </View>

        <Modal
          visible={modalVisible}
          transparent={true}
          animationType="fade"
          onRequestClose={() => setModalVisible(false)}>
          <View style={styles.modalContainer}>
            <View style={styles.modalContent}>
              <View style={{flexDirection: 'row'}}>
                <Text style={styles.title}>Establishment Details</Text>
                <TouchableOpacity onPress={() => setModalVisible(false)}>
                  <Icon name="close-outline" size={24} color="red" />
                </TouchableOpacity>
              </View>
              <View style={{alignSelf: 'flex-start'}}>
                <Text>User: {establishment.user}</Text>
                <Text>Generated By: {establishment.generatedBy}</Text>
              </View>
              <Image
                source={{uri: establishment.banner}}
                style={styles.modalBanner}
              />
              <View style={{alignSelf: 'flex-start'}}>
                <Text>
                  Location:{' '}
                  <Text
                    style={styles.link}
                    onPress={() =>
                      Linking.openURL(establishment.googleReviewUrl)
                    }>
                    View on Google Maps
                  </Text>
                </Text>
                <Text>Date: {establishment.date}</Text>
              </View>
            </View>
          </View>
        </Modal>

        <Modal
          visible={deleteModalVisible}
          transparent={true}
          animationType="fade"
          onRequestClose={() => setDeleteModalVisible(false)}>
          <View style={styles.modalContainer}>
            <View style={[styles.modalContent, {width: '80%'}]}>
              <Text style={styles.titleDelete}>Confirm Deletion</Text>
              <Text style={{textAlign: 'center'}}>
                Are you sure you want to delete this{'\n'} establishment?
              </Text>
              <View style={styles.modalActions}>
                <Button
                  title="Cancel"
                  onPress={() => setDeleteModalVisible(false)}
                />
                <Button title="Delete" onPress={handleDelete} color="red" />
              </View>
            </View>
          </View>
        </Modal>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerStyle: {
    paddingLeft: 18,
    backgroundColor: color.secondaryBG,
    marginBottom: 0,
    paddingTop: 4,
  },
  card: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: color.white,
    marginVertical: 8,
    borderRadius: 8,
    elevation: 3,
    marginHorizontal: 20,
  },
  infoSection: {flex: 1, justifyContent: 'center', marginLeft: 12},
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    lineHeight: 22,
    color: color.primaryText,
  },
  titleDelete: {
    fontSize: 18,
    fontWeight: 'bold',
    lineHeight: 22,
    color: color.secondaryTexts,
  },

  emaiStyle: {fontSize: 14, lineHeight: 18, color: '#555', flex: 1},
  generatedBy: {
    fontSize: 14,
    lineHeight: 18,
    color: '#555',
    flex: 1,
    marginTop: 5,
  },
  actionButtons: {flexDirection: 'row', marginTop: 8, gap: 12},
  iconButton: {padding: 4},
  banner: {width: 100, height: 100, borderRadius: 8},
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    width: '90%',
  },
  modalActions: {flexDirection: 'row', gap: 25, marginTop: 15},
  modalBanner: {
    width: '100%',
    height: 200,
    borderRadius: 8,
    marginVertical: 10,
  },
  link: {color: '#007BFF', textDecorationLine: 'underline'},
});

export default EstablishmentList;
