export default {
  Splash: 'Splash',
  SignUp: 'Login',
  Login: 'Login',
  IconAnimation: 'IconAnimation',
  UserType: 'UserType',
  BusinessType: 'BusinessType',
  CreateAccount: 'CreateAccount',
  DocumentUpload: 'DocumentUpload',
  HomeBottomTabs: 'HomeBottomTabs',
  ProductScreen: 'ProductScreen',
  VendorsScreen: 'VendorsScreen',
  VendorsDetails: 'VendorsDetails',
  ProductDetails: 'ProductDetails',
  Notification: 'Notification',
  AddToCart: 'AddToCart',
  TimeSlot: 'TimeSlot',
  AddCoupon: 'AddCoupon',
  OrderSuccessScreen: 'OrderSuccessScreen',
};
